### PR TITLE
JENKINS-49785 - Add param for export changelog filename.

### PR DESCRIPTION
**Pull request by LinuxSuRen**
[JENKINS-49785](https://issues.jenkins-ci.org/browse/JENKINS-49785)

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
@jenkinsci/code-reviewers

**Comment by LinuxSuRen** [comment]
@jenkinsci/code-reviewers

**Comment by LinuxSuRen** [comment]
I don't understand why the file name can't be exposed to scripts. Can you tell more details? Thanks.
@jglick

**Comment by LinuxSuRen** [comment]
@oleg-nenashev Can you help me to understand the context, please.

**Comment by daniel-beck** [comment]
JENKINS_HOME contents should generally be considered internal and subject to change at any time; so it makes little sense to expose information about them.

Not to mention that making use of this information almost certainly means you approved code in your Groovy sandbox that cannot be generally recommended for approval, like `File` related APIs.

**Comment by LinuxSuRen** [comment]
But I just export changelog path as String, it's not a object.

**Comment by daniel-beck** [comment]
@linuxsuren Yes, and whatever you do with that string is likely something we should not encourage.

**Comment by LinuxSuRen** [comment]
Ok, how can I get the changelog file' name, do you have any suggestion?

**Comment by LinuxSuRen** [comment]
I will checkout several repo in a pipeline script. so I need to know every changelog file names.

**Comment by daniel-beck** [comment]
@linuxsuren You have not explained what you need it for, this change lacks justification.

**Comment by LinuxSuRen** [comment]
I will do incremental build base on the changelog file.

**Comment by daniel-beck** [comment]
Which means you plan to open and parse files on the Jenkins master, which typically requires you to whitelist `File` related APIs or use whole-script approval, and that's not something we should encourage.

I recommend this PR be closed. There's nothing wrong with builds scripts knowing changelog contents, but it shouldn't be exposed in a way that encourages master file system access from a pipeline.

**Comment by LinuxSuRen** [comment]
I'am not use `File` to parse changelog file. instead of Python script.

**Comment by MarkEWaite** [comment]
@dwnusbaum this pull request should be closed based on the concerns expressed earlier in the PR comments

**Pull request closed without merging**
