### PR TITLE
Bump plugin parent POM from 4.19 to 4.33

### PR DESCRIPTION
**Pull request by basil**
Supersedes #65.

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]

**Comment by MarkEWaite** [comment]
Also supersedes #58

**Comment by basil** [comment]
@car-roll Is there a reason why this PR has remained unacknowledged for 3 months?

**Review by car-roll — APPROVED** [review]

**Comment by basil** [comment]
@car-roll Thank you so much for merging this PR. If time allows, would you also be able to do a release to help us with PCT testing of Java 17?

**Comment by basil** [comment]
Thank you!

**Pull request merged**
