### PR TITLE
[FIXED JENKINS-46597] Finally fix root cause by getting rid of TreeMap

### PR DESCRIPTION
**Pull request by abayer**
[JENKINS-46597](https://issues.jenkins-ci.org/browse/JENKINS-46597)

TreeMap$Entry isn't serializable, so returning a TreeMap from
checkout(scm) opens up a bunch of possible problems. Switching to a
HashMap fixes that.

cc @reviewbybees

### CODE REVIEW

**Comment by tru** [comment]
We ran into this problem in our environment since we saved the output from the scm step to a variable (which we then passed to useEnv). I just built the plugin locally with this patch and it seemed to have fixed the issue. A full build is now running again on our systems. I will verify that it goes through (but usually it was aborted at this point) and update again - but right now I feel pretty comfortable to say that this patch fixes our problems. Thanks for tracking that down!

**Comment by abayer** [comment]
Truly weird that the test works with `HashMap` but not `TreeMap`, then...hrm.

**Comment by abayer** [comment]
@jglick Ok, got it (I think) - see https://github.com/jenkinsci/workflow-cps-plugin/pull/189

**Comment by abayer** [comment]
Closed in favor of https://github.com/jenkinsci/workflow-cps-plugin/pull/189

**Pull request closed without merging**
